### ISSUE TITLE
Make library available on http://jcenter.bintray.com/

### ISSUE THREAD

**Issue by friederbluemle** [twofortyfouram/android-plugin-api-for-locale#1]
Is there a specific reason why this library is not available through the standard `jcenter()` declaration in an Android build.gradle file (which is sufficient for most other Android libraries)? Currently, it needs an additional maven repo to be declared. It would be great to have it available from jcenter.bintray.com
Thanks.

**Comment by sschuberth** [comment]
Out of curiosity, what is the additional Maven repository URL you're using? Are you linking to the GitHub releases page?

**Comment by ccjernigan** [comment]
This is a great suggestion, and is now complete.  We should have responded sooner to let you know that this was underway.  If you have future suggestions, please let us know!

Our delay was a partially related to getting all libraries migrated to JCenter at once.  The good news is that the the [plugin-client-sdk](https://github.com/twofortyfouram/android-plugin-client-sdk-for-locale) is also on JCenter now.

We also encountered some bugs in JCenter itself that delayed completing this.  JFrog provided us great support in getting those bugs squashed, so now we're all set.

Give the newly published dependencies a try!  We're excited to see the plug-ins you build!

**Comment by friederbluemle** [comment]
Awesome, thanks @ccjernigan
